# Generated by Django 4.1.6 on 2023-03-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guests', '0004_alter_shop_photo_alter_shop_proof'),
        ('Admin', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='Operatorphoto/')),
                ('proof', models.FileField(upload_to='Operatorproof/')),
                ('password', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.shop')),
            ],
        ),
    ]
