# Generated by Django 4.1.6 on 2023-03-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='password',
        ),
    ]
