# Generated by Django 4.1.6 on 2023-03-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0004_alter_shop_photo_alter_shop_proof'),
        ('Admin', '0007_complainttype'),
        ('Shops', '0002_remove_operator_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Excavatorsphoto/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.shop')),
                ('shoptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.shoptype')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subcategory')),
            ],
        ),
    ]
