# Generated by Django 4.1.6 on 2023-03-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_brand_brandtype_and_more'),
        ('Shops', '0003_excavator'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavator',
            name='brandtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.brandtype'),
        ),
    ]
