# Generated by Django 4.1.6 on 2023-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0004_excavator_brandtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavator',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
