# Generated by Django 4.1.6 on 2023-03-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0005_excavator_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
