# Generated by Django 4.1.6 on 2023-03-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0005_shop_shop_vsts'),
        ('Admin', '0009_rename_brand_brandtype_and_more'),
        ('Shops', '0006_delete_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='Operatorphoto/')),
                ('proof', models.FileField(upload_to='Operatorproof/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.shop')),
            ],
        ),
    ]
