# Generated by Django 4.1.6 on 2023-03-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_requestoperator'),
        ('Shops', '0007_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_vsts', models.IntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.operator')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.requestoperator')),
            ],
        ),
    ]
