# Generated by Django 4.1.6 on 2023-04-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0008_assignoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='ExcavatorsGallery/')),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.excavator')),
            ],
        ),
    ]
