# Generated by Django 4.1.6 on 2023-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoptype', models.CharField(max_length=50)),
            ],
        ),
    ]
