# Generated by Django 4.1.6 on 2023-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_shoptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintyp', models.CharField(max_length=50)),
            ],
        ),
    ]
