# Generated by Django 4.1.6 on 2023-03-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brandtype',
        ),
        migrations.RenameField(
            model_name='brandtype',
            old_name='brand',
            new_name='brandtype',
        ),
    ]
