# Generated by Django 4.1.6 on 2023-04-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0005_shop_shop_vsts'),
        ('Admin', '0009_rename_brand_brandtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_details', models.CharField(max_length=100)),
                ('feedback_date', models.DateField(auto_now=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guests.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guests.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.CharField(max_length=100)),
                ('complaint_date', models.DateField(auto_now=True)),
                ('complaint_vsts', models.IntegerField(default=0)),
                ('complaint_replay', models.CharField(max_length=100)),
                ('complainttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.complainttype')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guests.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guests.user')),
            ],
        ),
    ]
