# Generated by Django 4.1.6 on 2023-03-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guests', '0005_shop_shop_vsts'),
        ('Shops', '0005_excavator_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_vsts', models.IntegerField(default=0)),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.excavator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.user')),
            ],
        ),
    ]
