# Generated by Django 4.1.6 on 2023-03-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0005_excavator_price'),
        ('Guests', '0005_shop_shop_vsts'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('from_date', models.DateField()),
                ('days', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=50)),
                ('renting_date', models.DateField(auto_now=True)),
                ('rent_vsts', models.IntegerField(default=0)),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.excavator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.user')),
            ],
        ),
    ]
