# Generated by Django 4.1.6 on 2023-03-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0005_shop_shop_vsts'),
        ('Users', '0002_renting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=50)),
                ('request_date', models.DateField(auto_now=True)),
                ('request_vsts', models.IntegerField(default=0)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.renting')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guests.user')),
            ],
        ),
    ]
