# Generated by Django 4.1.6 on 2023-02-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_pass',
        ),
    ]
