# Generated by Django 4.1.6 on 2023-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.FileField(upload_to='shopphoto/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='proof',
            field=models.FileField(upload_to='shopproof/'),
        ),
    ]
