# Generated by Django 4.1.6 on 2023-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guests', '0004_alter_shop_photo_alter_shop_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_vsts',
            field=models.IntegerField(default=0),
        ),
    ]
